name: Buat Shortlink dari Issue

on:
  issues:
    types: [opened]

permissions:
  contents: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ambil data Issue
        id: issue
        uses: actions/github-script@v7
        with:
          script: |
            const slug = context.payload.issue.title.trim()
            const body = context.payload.issue.body.trim()
            return { slug, url: body }
          result-encoding: string

      - name: Buat file JSON shortlink
        run: |
          mkdir -p shorts
          echo "{\"url\": \"${{ steps.issue.outputs.url }}\"}" > "shorts/${{ steps.issue.outputs.slug }}.json"

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add shorts/
          git commit -m "Tambah shortlink ${{ steps.issue.outputs.slug }}"
          git push

      - name: Komentar di Issue
        uses: actions/github-script@v7
        with:
          script: |
            const slug = context.payload.issue.title.trim()
            const url = `https://${context.repo.owner}.github.io/${context.repo.repo}/s/${slug}`
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `✅ Shortlink jadi: ${url}`
            })
            github.rest.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "closed"
            })
